modules:
- logger
- pads
- teleport
- portals
- permissions
- chat
- signcolors
- joinspawn
- onlyproxyjoin
- hubcommand
- hidestream
- autosave
- adminmode
- bans
server-name: null
chat:
  default-format: '&7[Guest] &8<player>&f: <message>'
  formats:
    testformat: '&4<player>&7: &c<message>'
database:
  hostname: localhost
  port: 3306
  username: butt
  password: hole
  database_name: Aurora