modules:
- logger
- pads
- teleport
- portals
- chat
- signcolors
- joinspawn
- onlyproxyjoin
- hubcommand
- hidestream
- autosave
- adminmode
- bans
- loghoppers
- menu
- menuitem
- signlinks
- punch
- trailselector
- arrowtp
- nametags
- superspeed
- kick
- blockcommands
- maintenancemode
- pingchat
- tokens
- announcer
- privatemessages
- cloudmessages
- broadcastfirstjoin
- creativepass
server-name: undefined
pretty-server-name: Undefined
command-shortcuts:
  t: thru
database:
  hostname: localhost
  port: 3306
  username: butt
  password: hole
  database_name: Aurora
