modules:
- logger
- pads
- teleport
- portals
- chat
- signcolors
- joinspawn
- onlyproxyjoin
- hubcommand
- hidestream
- autosave
- adminmode
- bans
server-name: null
database:
  hostname: localhost
  port: 3306
  username: butt
  password: hole
  database_name: Aurora