modules:
- logger
- pads
- teleport
- portals
- chat
- signcolors
- joinspawn
- onlyproxyjoin
- hubcommand
- hidestream
- autosave
- adminmode
- bans
- loghoppers
- menu
- signlinks
- punch
- trailselector
- arrowtp
- nametags
- superspeed
server-name: undefined
pretty-server-name: Undefined
database:
  hostname: localhost
  port: 3306
  username: butt
  password: hole
  database_name: Aurora
