modules:
- logger
- pads
- teleport
- portals
- permissions
- chat
- signcolors
- joinspawn
- onlyproxyjoin
- hubcommand
- hidestream
- autosave
- adminmode
chat:
  default-format: '&7[Guest] &8<player>&f: <message>'
  formats:
    testformat: '&4<player>&7: &c<message>'