name: ${project.name}
main: ${project.groupId}.${upload.dbo.slug}.${project.name}
version: ${project.version}
description: ${project.description}
softdepend: [MilkyWay, zPermissions, WorldGuard, Vault, Votifier]
commands:
  ${upload.dbo.slug}:
    description: The central command for the ${project.name} plugin.
    usage: /<command> [args]
  teleport:
    description: Teleport to another player.
    usage: /<command> [args]
    aliases: [tp]
  teleporthere:
    description: Teleport another player to yourself.
    usage: /<command> [args]
    aliases: [tphere]
  teleportaccept:
    description: Accept a teleport request.
    usage: /<command> [args]
    aliases: [tpaccept,tpa]
  teleporttoggle:
    description: Toggle receiving teleport requests.
    usage: /<command> [args]
    aliases: [tptoggle,tpt]
  adminmode:
    description: Admin mode.
    usage: /<command> [args]
    aliases: [a]
  launchpad:
    description: Launch pads!
    usage: /<command> [args]
    aliases: [lp]
  bc:
    description: Block commands!
    usage: /<command> [args]
  s:
    description: Server menu!
    usage: /<command> [args]
  clearchat:
    description: Clear chat!
    usage: /<command> [args]
    aliases: [cc]
  farmworld:
    description: Farmworld!
    usage: /<command> [args]
  broadcast:
    description: Broadcast!
    usage: /<command> [args]
  help:
    description: Help!
    usage: /<command> [args]
  vote:
    description: Vote!
    usage: /<command> [args]
  member:
    description: Member!
    usage: /<command> [args]
  rules:
    description: Rules!
    usage: /<command> [args]
  tos:
    description: TOS!
    usage: /<command> [args]
  privacy:
    description: Privacy!
    usage: /<command> [args]
  store:
    description: Store!
    usage: /<command> [args]
    aliases: [buy]
  livemap:
    description: Livemap!
    usage: /<command> [args]
  mumble:
    description: Mumble!
    usage: /<command> [args]
